import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-center items-center py-4 gap-10 bg-gray-700">
          <Link 
            href="/"
            className="text-lg text-blue-400 underline underline-offset-2 "
          >
            Home
          </Link>
          <Link
            href="/posts"
            className="text-lg text-blue-400 underline underline-offset-2 "
          >
            Posts
          </Link>
          <Link
            href="/articles"
            className="text-lg text-blue-400 underline underline-offset-2 "
          >
            Articles
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
